name: scanify
description: "A production-ready Flutter document scanning app with native OpenCV."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  get: ^4.7.3

  # Local DB
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.6

  # ML Kit
  google_mlkit_face_detection: ^0.13.2
  google_mlkit_text_recognition: ^0.15.1

  # Image
  image: 4.9.1
  image_picker: ^1.2.1

  # PDF
  pdf: ^3.11.3
  printing: ^5.15.0

  # Architecture
  equatable: ^2.0.8
  dartz: ^0.10.1

  # Utils
  uuid: ^4.5.2
  intl: ^0.20.3
  permission_handler: ^12.0.3

  # Open and Share
  open_filex: ^4.7.0
  share_plus: ^13.2.0

  # Splash screen (runtime removal)
  flutter_native_splash: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.11.1
  hive_ce_generator: 1.11.2
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0

  # Icon + Splash generation
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  # Android adaptive icon
  adaptive_icon_background: "#1A1A2E"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"


flutter_native_splash:
  # Light mode
  color: "#1A1A2E"
  image: assets/splash/logo.png

  # Dark mode
  color_dark: "#0D0D1A"
  image_dark: assets/splash/logo.png

  # Android 12+ themed splash
  android_12:
    image: assets/splash/logo.png
    color: "#1A1A2E"
    icon_background_color: "#1A1A2E"
    image_dark: assets/splash/logo.png
    color_dark: "#0D0D1A"
    icon_background_color_dark: "#0D0D1A"

  fullscreen: true
  android: true
  ios: true

# ── Flutter ───────────────────────────────────────────────────────────────────
flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/splash/