import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:hive_ce_flutter/adapters.dart';

import 'core/constants/app_constants.dart';
import 'core/routes/app_pages.dart';
import 'core/routes/app_routes.dart';
import 'core/theme/app_theme.dart';
import 'features/home/data/models/history_item_model.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await _initHive();
  runApp(const ScanifyApp());
}

Future<void> _initHive() async {
  await Hive.initFlutter();

  // Register adapters — generated by build_runner
  if (!Hive.isAdapterRegistered(0)) {
    Hive.registerAdapter(HistoryItemModelAdapter());
  }

  // Open boxes
  await Hive.openBox<HistoryItemModel>(AppConstants.historyBoxName);
}

class ScanifyApp extends StatelessWidget {
  const ScanifyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: AppConstants.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      initialRoute: AppRoutes.home,
      getPages: AppPages.pages,
      defaultTransition: Transition.cupertino,
    );
  }
}
